# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd0f0f069bf5c67b831fd0fa9276e2afce940207110b27d0e74e19beeca87f0cc61626070952c854ec85b6a55d8e96a00adffcac936188aaf6b997374bd6704a

test:
  secret_key_base: 2ca12c866ce421da0668b05ed72b319b30d90a1f0578737d14cd307c00b8473e10bfe11dba4816a56eab3a2c4289f93c4f06d2cf4cbb05b618137e82f93ebb4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
